kind: "BuildConfig"
apiVersion: "build.openshift.io/v1"
metadata:
  name: "simple-oracldedb-pipeline"
spec:
  source:
    contextDir: simple-pipeline
    git:
      uri: "https://github.com/migutak/oracledb_node"
      ref: "master"
    strategy:
      jenkinsPipelineStrategy:
        type: JenkinsPipeline